//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VideoStoreEntities : DbContext
    {
        public VideoStoreEntities()
            : base("name=VideoStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    
        public virtual int AddVideo(string videoTitle, Nullable<System.DateTime> videoReleaseDate, string videoGenre, string videoPrice)
        {
            var videoTitleParameter = videoTitle != null ?
                new ObjectParameter("VideoTitle", videoTitle) :
                new ObjectParameter("VideoTitle", typeof(string));
    
            var videoReleaseDateParameter = videoReleaseDate.HasValue ?
                new ObjectParameter("VideoReleaseDate", videoReleaseDate) :
                new ObjectParameter("VideoReleaseDate", typeof(System.DateTime));
    
            var videoGenreParameter = videoGenre != null ?
                new ObjectParameter("VideoGenre", videoGenre) :
                new ObjectParameter("VideoGenre", typeof(string));
    
            var videoPriceParameter = videoPrice != null ?
                new ObjectParameter("VideoPrice", videoPrice) :
                new ObjectParameter("VideoPrice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddVideo", videoTitleParameter, videoReleaseDateParameter, videoGenreParameter, videoPriceParameter);
        }
    
        public virtual int AddNewCustomer(string customerName, string customerEmail, string customerPhone, Nullable<int> customerOrder)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var customerEmailParameter = customerEmail != null ?
                new ObjectParameter("CustomerEmail", customerEmail) :
                new ObjectParameter("CustomerEmail", typeof(string));
    
            var customerPhoneParameter = customerPhone != null ?
                new ObjectParameter("CustomerPhone", customerPhone) :
                new ObjectParameter("CustomerPhone", typeof(string));
    
            var customerOrderParameter = customerOrder.HasValue ?
                new ObjectParameter("CustomerOrder", customerOrder) :
                new ObjectParameter("CustomerOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNewCustomer", customerNameParameter, customerEmailParameter, customerPhoneParameter, customerOrderParameter);
        }
    
        public virtual ObjectResult<spRetrieveCustomerByName_Result> RetrieveCustomerByName(string customerName)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRetrieveCustomerByName_Result>("RetrieveCustomerByName", customerNameParameter);
        }
    }
}
